export const enum NoticeStatus {
  MAINTENANCE_NOT_STARTED_YET,
  MAINTENANCE_IN_PROGRESS,
  MAINTENANCE_COMPLETED,
  INCIDENT_INVESTIGATING,
  INCIDENT_IDENTIFIED,
  INCIDENT_MONITORING,
  INCIDENT_RESOLVED,
}
